### ISSUE TITLE
how to get notebookdata 

### ISSUE THREAD

**Issue by RachelHui12** [MarcCoru/crop-type-mapping#6]
When I click the `notebookdata` URL 'https://syncandshare.lrz.de/dl/fiM6b3e7eeyFAGWmAHEeoeBB/notebookdata.zip', it shows HTTP ERROR 404. I download these data on Windows platform, so I can only obtain these data manually.

**Comment by MarcCoru** [comment]
Hello,

thank you for pointing this out.
The correct link is https://zenodo.org/record/5707142/files/notebookdata.zip?download=1

I just updated the download.sh script in the latest commit
